{
 "title": "Home",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "HTTP Codes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\r\n        |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n        |> filter(fn: (r) =>\r\n            r._measurement == \"traefik.entrypoint.requests.total\" and\r\n            r.entrypoint == \"http\"\r\n        )\r\n        |>group(columns: [\"code\"])\r\n        |>count()\r\n        |>drop(columns: [\"_start\", \"_stop\"])\r\n        |> rename(columns: {_value: \"http code\"})\r\n        "
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "// v.windowPeriod is a variable referring to the current optimized window period (currently: $interval)\nfrom(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"traefik.entrypoint.request.duration\")\n  |> filter(fn: (r) => r[\"entrypoint\"] == \"http\" and r[\"protocol\"] != \"websocket\")\n  |> filter(fn: (r) => r[\"_field\"] == \"p90\")\n  |> group()\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> map(fn: (r) => ({r with _value:  r._value * 1000.0 }))"
    }
   ]
  },
  {
   "title": "Entrypoint request overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\r\n        |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n        |> filter(fn: (r) =>\r\n            r._measurement == \"traefik.entrypoint.requests.total\"\r\n        )\r\n        |> group(columns: [\"entrypoint\", \"method\", \"protocol\"])\r\n        |> drop(columns: [\"_start\", \"_stop\"])"
    }
   ]
  }
 ]
}